# Generated by Django 3.2.4 on 2021-07-07 20:35

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_frecuencia', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_gerencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitador', models.BooleanField(default=False)),
                ('coordinador', models.BooleanField(default=False)),
                ('alumno', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('contenido', models.TextField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.duracion')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frecuencia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosCapacitacion',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.create_path_capacitaciones)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capacitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.create_path)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
            ],
        ),
    ]
