# Generated by Django 3.2.4 on 2021-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencia',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
