# Generated by Django 3.2.4 on 2021-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
