# Generated by Django 3.2.4 on 2021-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210701_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
