# Generated by Django 3.2.4 on 2021-07-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gerencia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.gerencia'),
            preserve_default=False,
        ),
    ]
