# Generated by Django 3.2.4 on 2021-07-13 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitaciones',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2021, 7, 13)),
        ),
    ]
