# Generated by Django 3.2.4 on 2021-07-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_archivos_archivostema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivosTema',
            new_name='Archivos',
        ),
    ]
