# Generated by Django 3.2.4 on 2021-07-13 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_capacitaciones_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 13)),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(9, 35, 55, 922116)),
        ),
        migrations.CreateModel(
            name='HitoAsistencia',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gerencia')),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hito')),
            ],
        ),
        migrations.AddField(
            model_name='hito',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capacitaciones'),
        ),
    ]
