# Generated by Django 3.2.4 on 2021-07-06 20:06

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_archivostema_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_frecuencia', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_topico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.duracion')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frecuencia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topico')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosCapacitacion',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.create_path_capacitaciones)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capacitaciones')),
            ],
        ),
    ]
