# Generated by Django 3.2.4 on 2021-07-13 14:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210713_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 0, 42, 293321)),
        ),
    ]
