# Generated by Django 3.2.4 on 2021-07-13 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210713_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 5, 10, 776100)),
        ),
    ]
