# Generated by Django 3.2.4 on 2021-07-13 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_capacitaciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 46, 16, 444401)),
        ),
    ]
