# Generated by Django 3.2.4 on 2021-07-13 19:44

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_capacitaciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 44, 42, 13944)),
        ),
        migrations.CreateModel(
            name='ArchivosHitos',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.create_path_hito)),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hito')),
            ],
        ),
    ]
