# Generated by Django 3.2.4 on 2021-07-13 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210713_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 43, 32, 780921)),
        ),
    ]
