# Generated by Django 3.2.4 on 2021-07-20 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_capacitaciones_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoshitos',
            name='hito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hito_archivos', to='core.hito'),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 54, 12, 969950)),
        ),
        migrations.AlterField(
            model_name='hitoasistencia',
            name='hito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asist', to='core.hito'),
        ),
    ]
